apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-earth-setting
spec:
  forms:
    - group: layout
      label: Loyout
      formSchema:
        - $formkit: select
          name: post_list_layout
          label: Articles Listing Layout
          value: grid_3
          options:
            - label: Grid（Three columns in a row）
              value: grid_3
            - label: Grid（One row, two columns）
              value: grid_2
            - label: Single Bar
              value: single
          help: "When single bar is selected，The image of the postcard will be on the left"
        - $formkit: select
          name: header_widget
          label: Homepage Top Blocks
          value: site_title
          options:
            - label: None
              value: none
            - label: Latest Posts
              value: latest_post
            - label: Post Grid（Five Latest Articles）
              value: latest_post_grid
            - label: The Site Title
              value: site_title
        - $formkit: select
          name: header_background_type
          id: header_background_type
          key: header_background_type
          label: Home Top Background
          value: image
          options:
            - label: Set manually
              value: manual
            - label: Infographic
              value: image
        - $formkit: text
          if: "$get(header_background_type).value === manual"
          name: header_background
          id: header_background
          key: header_background
          label: Home Top Background
        - $formkit: attachment
          if: "$get(header_background_type).value === image"
          name: header_background_image
          id: header_background_image
          key: header_background_image
          label: Homepage Top Background Image
          value: /themes/theme-earth/assets/images/default-background-2023-10-12.jpeg
        - $formkit: radio
          name: content_header
          label: Top of Article Page
          value: true
          options:
            - label: Show
              value: true
            - label: Hide
              value: false

    - group: style
      label: Style
      formSchema:
        - $formkit: radio
          name: color_scheme
          label: Base Color Scheme
          value: system
          options:
            - label: Follow system
              value: system
            - label: Dark
              value: dark
            - label: Light
              value: light

        - $formkit: checkbox
          name: enable_change_color_scheme
          label: Allow visitors to toggle color scheme
          value: true

    - group: post
      label: Posts
      formSchema:
        - $formkit: select
          name: content_style
          label: Content & Style
          value: "tailwind"
          options:
            - label: GitHub STYLE #
              value: github
            - label: Tailwind CSS Typography
              value: tailwind
        - $formkit: repeater
          name: share_items
          label: Share buttons
          value:
            - id: wechat
            - id: x
            - id: telegram
            - id: facebook
            - id: qq
            - id: qzone
            - id: weibo
            - id: douban
            - id: native
          children:
            - $formkit: select
              name: id
              label: Sharing platform
              options:
                - label: WeChat
                  value: wechat
                - label: X
                  value: x
                - label: Telegram
                  value: telegram
                - label: Facebook
                  value: facebook
                - label: QQ
                  value: qq
                - label: QQ Space
                  value: qzone
                - label: Weibo
                  value: weibo
                - label: Douban
                  value: douban
                - label: System Sharing
                  value: native
    - group: sidebar
      label: Sidebar
      formSchema:
        - $formkit: repeater
          name: widgets
          label: Widgets
          value:
            - value: popular-posts
            - value: categories
            - value: tags
          children:
            - $formkit: select
              name: value
              label: Parts
              options:
                - label: Site Profile
                  value: profile
                - label: Trending Articles
                  value: popular-posts
                - label: Article Categories
                  value: categories
                - label: In Post Tag
                  value: tags

        - $formkit: group
          name: profile
          value:
            logo:
          children:
            - $formkit: attachment
              name: logo
              label: Site Profile Logo

        - $formkit: repeater
          name: social_media
          label: Social media
          value: []
          children:
            - $formkit: select
              name: icon
              label: Icon
              options:
                - label: Email
                  value: i-tabler-mail
                - label: WeChat
                  value: i-simple-icons-wechat
                - label: Tencent QQ
                  value: i-simple-icons-tencentqq
                - label: Sina Weibo
                  value: i-simple-icons-sinaweibo
                - label: Zhihu
                  value: i-simple-icons-zhihu
                - label: Douban
                  value: i-simple-icons-douban
                - label: bilibili
                  value: i-simple-icons-bilibili
                - label: Tik Tok
                  value: i-simple-icons-tiktok
                - label: Telegram
                  value: i-simple-icons-telegram
                - label: Facebook
                  value: i-simple-icons-facebook
                - label: Instagram
                  value: i-simple-icons-instagram
                - label: LinkedIn
                  value: i-simple-icons-linkedin
                - label: Twitter
                  value: i-simple-icons-twitter
                - label: Slack
                  value: i-simple-icons-slack
                - label: Discord
                  value: i-simple-icons-discord
                - label: YouTube
                  value: i-simple-icons-youtube
                - label: Steam
                  value: i-simple-icons-steam
                - label: GitHub
                  value: i-simple-icons-github
                - label: GitLab
                  value: i-simple-icons-gitlab
                - label: RSS
                  value: i-simple-icons-rss
            - $formkit: text
              name: name
              label: <g id="Bold">Medicine Name </g>
            - $formkit: text
              name: url
              label: Link
              validation: "required"
            - $formkit: radio
              name: url_type
              label: link type
              value: normal
              help: "If image type is selected，Then, after the visitor clicks, it will be loaded in the form of a pop-up box"
              options:
                - label: Jump link
                  value: normal
                - label: Infographic
                  value: image

    - group: footer
      label: Footer
      formSchema:
        - $formkit: select
          name: style
          id: style
          key: style
          label: General footer
          value: style_1
          options:
            - label: Style One
              value: style_1
            - label: Style Two
              value: style_2

        - $formkit: attachment
          name: logo
          label: Logo
          help: If not set，will use the set of Logo

        - $formkit: text
          name: title
          label: Title
          help: If not set，The title set by the site will be used

        - $formkit: textarea
          rows: 3
          name: slogan
          id: slogan
          key: slogan
          if: "$get(style).value === style_2"
          label: Tagline menu

        - $formkit: menuRadio
          if: "$get(style).value === style_1"
          name: menu
          id: menu
          key: menu
          label: Right-hand Menu

        - $formkit: repeater
          if: "$get(style).value === style_2"
          name: menus
          id: menus
          key: menus
          label: Menu groups
          value: []
          children:
            - $formkit: menuRadio
              name: name
              label: Menu
              validation: "required"

        - $formkit: repeater
          name: social_media
          label: Social media
          value: []
          children:
            - $formkit: select
              name: icon
              label: Icon
              options:
                - label: Email
                  value: i-tabler-mail
                - label: WeChat
                  value: i-simple-icons-wechat
                - label: Tencent QQ
                  value: i-simple-icons-tencentqq
                - label: Sina Weibo
                  value: i-simple-icons-sinaweibo
                - label: Zhihu
                  value: i-simple-icons-zhihu
                - label: Douban
                  value: i-simple-icons-douban
                - label: bilibili
                  value: i-simple-icons-bilibili
                - label: Tik Tok
                  value: i-simple-icons-tiktok
                - label: Telegram
                  value: i-simple-icons-telegram
                - label: Facebook
                  value: i-simple-icons-facebook
                - label: Instagram
                  value: i-simple-icons-instagram
                - label: LinkedIn
                  value: i-simple-icons-linkedin
                - label: Twitter
                  value: i-simple-icons-twitter
                - label: Slack
                  value: i-simple-icons-slack
                - label: Discord
                  value: i-simple-icons-discord
                - label: YouTube
                  value: i-simple-icons-youtube
                - label: Steam
                  value: i-simple-icons-steam
                - label: GitHub
                  value: i-simple-icons-github
                - label: GitLab
                  value: i-simple-icons-gitlab
                - label: RSS
                  value: i-simple-icons-rss
            - $formkit: text
              name: name
              label: <g id="Bold">Medicine Name </g>
            - $formkit: text
              name: url
              label: Link
              validation: "required"
            - $formkit: radio
              name: url_type
              label: link type
              value: normal
              help: "If image type is selected，Then, after the visitor clicks, it will be loaded in the form of a pop-up box"
              options:
                - label: Jump link
                  value: normal
                - label: Infographic
                  value: image

    - group: beian
      label: Filing Settings
      formSchema:
        - $formkit: text
          name: icp_text
          label: ICPFiling Number
        - $formkit: text
          name: icp_link
          label: ICPFiling redirect link
          value: https://beian.miit.gov.cn/

        - $formkit: text
          name: gongan_text
          label: Public Security Network Record Number
        - $formkit: text
          name: gongan_link
          label: Public Security Network Filing Jump Link
          value: https://beian.mps.gov.cn/#/query/webSearch
